### ISSUE TITLE
Storage layer: manage collections

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/bcdb#4]
Collections (zdb namespaces) should be managed so that we can separate them based on the threebot id of the client. This way we can save backups of other threebots in the db. One solution would be to modify the collection name from the user to be `$threebotid_$collectionname` where `collectionname` is the name of the collection as specified by the user.

**Comment by muhamadazmy** [comment]
can we use the `:` as a separator instead of `_` because it looks ugly and not readable. so i suggest `<threebot-id>:<collection-name>` instead

**Comment by muhamadazmy** [comment]
According to last meeting with Kristof, we should not save other bcdb data locally, instead they are fetched from the remote bcdbs when needed
