### ISSUE TITLE
metadata should be stored in zdb as well, not only indexed

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/bcdb#55]
This is to allow users, and remote entities to do a 'global' get with just a unique ID without knowing which collection to use. the idea is to have a `<user-id>.<object-id> ` which is unique to any object stored, without knowing the type.

**Comment by muhamadazmy** [comment]
Currently metadata is stored in the index using a 'collection' type. It's either we change this so all meta share the same index. and the collection become an extra tag. 
Or the other (and probably the trickier) solution is to also store metadata in zdb.

**Comment by muhamadazmy** [comment]
# Proposal
- in ZDB we have to maintain `objects` namespace, and `metadata` namespace
- On object SET, the data is stored in the `objects` we get an ID back `data-id` 
- We create a meta object, and store the `data-id` on the meta.
- The meta is then stored in the `metadata` namespace, which returns `meta-id`
  - The meta-id is not stored anywhere, hence there is no way to map data to meta directly without scanning the metadata namespace.
-  The metadata is then indexed normally.
  - We will move all metadata for all "collections" to a single metadata store, hence the `collection` will become an extra tag.

## On Get
Data can be retrieved from zdb via global ID. also metadata can be retrieved from the index store, if collection is provided the collection is added to the tags list for both get and find operations.

**Comment by zaibon** [comment]
I don't get this. I though any object stored in BCDB already receives a unique ID. The base idea of BCDB was to be able to address any content with just 2 integer `<user-id>.<object-id>`. At what point is this ID became link to the collection ?

**Comment by muhamadazmy** [comment]
When I added the metadata, I stored separate metadata objects in separate "stores". So metadata is separated at the index level in `collections` hence while u still can get an object with unique id, the metadata requires the knowledge of what collection the object is stored in. 

I will make the collection concept virtual, so a collection is another reserved tag in the metadata. So you still can do find operation in a specific collection, but still be able to globally get an object.

**Comment by muhamadazmy** [comment]
The rest of the changes described above (store the metadata in zdb) so we can be able to rebuild the index from zdb alone.

**Comment by zaibon** [comment]
> When I added the metadata, I stored separate metadata objects in separate "stores". 

But this is for `find` command only right ? when you want to look for something based on its tags/metadata. Today can we already address all content form a BCDB using just  `<user-id>.<object-id>` or not ?

**Comment by muhamadazmy** [comment]
Not, but this is being fixed right now. All the code is there, i just need to add the grpc method, and the rest endpoint as well
