### ISSUE TITLE
BCDB should not relay on the explorer to authenticate request from its owner

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/bcdb#56]
Today, any request coming in makes BCDB ask the public key of the associated threebot ID from the explorer.
I think we should and can avoid that since BCDB does have the public key of itself already.

This would allow BCDB to work in an offline mode (at least for request coming directly to him)

**Comment by muhamadazmy** [comment]
Note that, while this fix will work to allow owner access to bcdb, if the user is not using an identity that is known by the explorer, other bcdbs (p2p) will not accept his requests
