### ISSUE TITLE
Create an interface to combine metadata and storage layers

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/bcdb#7]
Although they are separate layers, they will inevitably interoperate and be combined together, since the metadata we save is tied to the data blob which gets saved in the storage layer, and in case of a write the ID used to save the metadata is only produced by the storage layer. 

For an api, it would be best to create a struct which takes both a storage implementation and a metadata implementation, and then exposes the basic methods from the storage layer, managing the metadata layer under the hood so the consumer of the struct does not need to care for this. Later on, whe can then define a query interface which first goes through the metadata, then uses the result to fetch the actual data from the storage

**Comment by muhamadazmy** [comment]
I still don't see why the API has to split between metadata and data. This will make using the client much harder, and non-atomic (to have to push data in one step, then attach meta). Please review the protobuf service definition I have added and we can improve from there.

**Comment by zaibon** [comment]
> This will make using the client much harder, and non-atomic

This issue is not about the public interface exposed by the grpc server but the internal API that is going to be used by the grpc server.

> To have to push data in one step, then attach meta

This is not how we said it would work. A data write has metadata attached with it. it is done in one single call. 
What is possible next to that, is to send more metadata on an existing object.

**Comment by muhamadazmy** [comment]
Yeah, okay that makes sense now.

**Comment by muhamadazmy** [comment]
Yes, this really need to be done now specially after introducing the REST api.
